export type Locale = "en" | "no";

export const navItems = [
  { href: "/", key: "home" },
  { href: "/cuts-and-services", key: "services" },
  { href: "/the-team", key: "team" },
  { href: "/portfolio", key: "portfolio" },
  { href: "/the-method", key: "method" },
  { href: "/shop", key: "shop" },
  { href: "/journal", key: "journal" },
  { href: "/visit", key: "visit" },
  { href: "/about", key: "about" },
] as const;

export const images = {
  heroAmara: "/images/hero-amara-chair.jpg",
  heroDaniel: "/images/hero-daniel-fade-coils.jpg",
  founder: "/images/founder-vanessa-working.jpg",
  stylist: "/images/team-stylist-portrait.jpg",
  stylistJonas: "/images/team-jonas.jpg",
  portfolioType4: "/images/portfolio-type4-after.jpg",
  portfolioType3: "/images/portfolio-type3a-after.jpg",
  portfolioSculpt: "/images/portfolio-sculpt-cut.jpg",
  portfolioExtra1: "/images/portfolio-extra-1.jpg",
  portfolioExtra2: "/images/portfolio-extra-2.jpg",
  portfolioExtra3: "/images/portfolio-extra-3.jpg",
  portfolioExtra4: "/images/portfolio-extra-4.jpg",
  method: "/images/method-dry-cut-detail.jpg",
  shop: "/images/shop-curl-shelf.jpg",
  visit: "/images/visit-salon-interior.jpg",
};

export const curlTypes = ["2A", "2B", "2C", "3A", "3B", "3C", "4A", "4B", "4C"];

const sharedServices = [
  { id: "first", price: "750 NOK", time: "90 min", featured: true },
  { id: "jackson", price: "750 NOK", time: "75 min", featured: true },
  { id: "sculpt", price: "850 NOK", time: "60 min", featured: true },
  { id: "sculpt-beard", price: "950 NOK", time: "75 min", featured: false },
  { id: "color", price: "1,200-2,200 NOK", time: "120+ min", featured: false },
  { id: "treatment", price: "350 NOK", time: "30 min", featured: false },
  { id: "consult", price: "0 NOK", time: "15 min", featured: false },
  { id: "kids", price: "350 NOK", time: "30 min", featured: false },
];

const sharedStylists = [
  {
    id: "any",
    // Use salon-interior for the "no preference" card so it reads as a
    // welcoming, collective option rather than a single stylist's detail.
    image: images.visit,
    tags: ["best fit", "all patterns"],
  },
  {
    id: "vanessa",
    image: images.founder,
    tags: ["4a-4c", "dry cuts", "training: Curl Bar + Devachan"],
  },
  {
    id: "iman",
    image: images.stylist,
    tags: ["color", "porosity", "shape reset"],
  },
  {
    id: "jonas",
    image: images.stylistJonas,
    tags: ["fade + coils", "taper", "line work"],
  },
];

export const content = {
  en: {
    messages: {
      app: { name: "Jackson & Coil", locale: "English" },
    },
    nav: {
      home: "Home",
      services: "Cuts",
      team: "Team",
      portfolio: "Portfolio",
      method: "Method",
      shop: "Shop",
      journal: "Journal",
      visit: "Visit",
      about: "About",
    },
    common: {
      skip: "Skip to content",
      primaryNav: "Primary navigation",
      mobileNav: "Mobile navigation",
      toggleLanguage: "Switch language",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      bookNow: "Book now",
      viewServices: "View services",
      readMethod: "Read the method",
      minutes: "minutes",
      price: "Price",
      duration: "Duration",
      next: "Next",
      back: "Back",
      confirm: "Confirm booking",
    },
    labels: {
      photographyRule: "Photography rule",
      method: "Method",
      founder: "Founder",
      portfolio: "Portfolio",
      proof: "Proof",
      proofTitle: "The standard, stated plainly.",
      verifiedClient: "Prototype voice · Curl client, Oslo",
      summary: "Summary",
      service: "Service",
      stylist: "Stylist",
      time: "Time",
      with: "with",
      nextAvailable: "Next available",
      available: "Available",
      core: "Core",
      openingHours: "Opening hours",
      closed: "Sun-Mon closed",
      location: "Grünerløkka, Oslo",
      noChemicalPlaceholder: "None / color / relaxer",
      wantPlaceholder: "Shape, length, definition, line",
      scaredPlaceholder: "Too short, shrinkage, uneven shape",
    },
    footer: {
      eyebrow: "Grünerløkka, Oslo",
      title: "Dry consultation first. Then the cut.",
      body: "A curl-specialist salon for the full spectrum, with prices on the page and booking that stays inside the brand.",
      visit: "Visit the salon",
      navigate: "Navigate",
      details: "Details",
    },
    home: {
      eyebrow: "Founded by Vanessa Jackson",
      title: "Oslo's first salon built around the curl spectrum.",
      lead: "From loose waves to tight coils, every pattern gets the same care, by stylists who actually trained for it.",
      proof: ["Free 15-minute dry consultation", "Type 2A-4C", "Prices shown before you book"],
      imageNote: "Hero rotation: Amara and Daniel, above the fold, not a separate men's lane.",
      band: "Spectrum is the operating word. One chair for coils, curls, waves, fades and shape-ups.",
      bookingTitle: "Booking is part of the haircut.",
      bookingBody: "Choose a service, a stylist, a real slot and your curl pattern without leaving the site. No widget redirect, no callback form.",
      servicesTitle: "Three doors in.",
      methodTitle: "The Jackson Cut maps the hair before it cuts.",
      methodBody: "Assessment, map, dry cut, finish, education. The method is visible because trust should not depend on vibes.",
      founderTitle: "Vanessa, working.",
      founderBody: "Trained at Curl Bar London and Devachan NYC. The salon is what happens when she stops borrowing chairs in other people's rooms.",
      portfolioTitle: "Same wall. Full spectrum.",
      portfolioBody: "Type 4 is the home base. Type 3 sits in the gallery. Daniel's Sculpt Cut is integrated from day one.",
      visitTitle: "A warm room, not a performance.",
      visitBody: "Paper walls, terracotta detail, real daylight, retail that solves the Norway gap.",
      testimonials: [
        { quote: "No one asked if my hair was too much.", attribution: "Amara O. · Type 4a · Tøyen" },
        { quote: "I booked on my phone after bedtime and had a time in under two minutes.", attribution: "Sigrid M. · Type 2c · Frogner" },
        { quote: "The fade and the coils happened in one chair.", attribution: "Daniel B. · Sculpt · Grünerløkka" },
        { quote: "Prices were there before I clicked anything.", attribution: "Maja H. · Type 3b · Sagene" },
      ],
    },
    servicesPage: {
      eyebrow: "Cuts and services",
      title: "One price, shown before the chair.",
      lead: "First visit includes the dry consultation. Color starts with a consultation. Men's work uses sculpt, taper, definition and line.",
      prepTitle: "Arrive dry, detangled, natural.",
      prep: "No hats, clips, braids, buns or stretched styles that change the pattern. Bring photos if they help. We need to see the hair before we touch it.",
      pricingTitle: "No guessing at checkout.",
      pricingBody: "Every service shows price and time. Color has a published range because the work is variable, but the consultation happens before any bill changes.",
    },
    methodPage: {
      eyebrow: "The method",
      title: "Dry first. Pattern visible. Cut second.",
      lead: "The Jackson Cut and The Sculpt Cut are built as teachable systems, not personality tricks.",
      steps: [
        ["Assess", "Curl type, density, porosity, growth direction and day-three reality."],
        ["Map", "Canopy, underlayer, nape and temple zones get different rules."],
        ["Cut", "Dry, curl by curl, without tension-stretching the pattern into a lie."],
        ["Finish", "Products you can buy in Norway and use at home without theatre."],
        ["Teach", "You leave knowing what changed and why."],
      ],
      diagramTitle: "We use Andre Walker's 2A to 4C scale during the dry consultation.",
      diagramBody: "It is not a label that defines you. It is a shared language so the stylist can prepare before you arrive.",
    },
    teamPage: {
      eyebrow: "The team",
      title: "Named stylists before the calendar.",
      lead: "Choose Vanessa, choose a specialist, or choose no preference. Nobody is penalized for wanting the best fit.",
    },
    aboutPage: {
      eyebrow: "Founder story",
      title: "The salon is what happens when Vanessa stops borrowing chairs.",
      lead: "North London training, New York technique, Oslo clients who were tired of flying out for a cut.",
      body: "Vanessa Jackson trained formally at Curl Bar London under Michelle Sultan, then crossed to New York for Devachan and Hair Rules influence. In Oslo she built a quiet client list from borrowed chairs. Jackson & Coil turns that chair into a flagship.",
      belief: "Every curl pattern is the same job done with knowledge, and knowledge is something you go and get.",
    },
    visitPage: {
      eyebrow: "Visit",
      title: "Grünerløkka, close to the tram, built for real appointments.",
      lead: "Warm light, square edges, no spa theatre. The room is calm because the work is specific.",
      directions: ["Tram 11, 12 or 13 to Olaf Ryes plass", "Five minutes from Birkelunden", "Step-free entrance planned", "Evening slots Tuesday to Friday"],
    },
    portfolioPage: {
      eyebrow: "Portfolio",
      title: "One gallery. No kids' table.",
      lead: "Filter by pattern if it helps, but the work sits together. The wall tells the truth in three seconds.",
      filters: ["All", "Type 4", "Type 3", "Sculpt Cut"],
    },
    shopPage: {
      eyebrow: "Shop",
      title: "The shelf Oslo has been missing.",
      lead: "A tight retail edit: curl products, durags, bonnets, twist sponges, beard picks and the boring essentials people actually rebuy.",
    },
    journalPage: {
      eyebrow: "Journal",
      title: "Short, useful, not content for its own sake.",
      lead: "Prep notes, product literacy, founder voice and community events. Written like someone who has stood behind the chair.",
    },
    bookingPage: {
      eyebrow: "Booking",
      title: "Book on your phone in two minutes.",
      lead: "Choose a service, stylist, and time. Confirm in two minutes.",
    },
    serviceNames: {
      first: ["First Visit Bundle", "Consultation + Jackson Cut + finish + first-time retail discount."],
      jackson: ["The Jackson Cut", "Dry, curl-by-curl cut for Type 2-4 hair."],
      sculpt: ["The Sculpt Cut", "Fade, lineup and dry coil shaping in one chair."],
      "sculpt-beard": ["Sculpt Cut + Beard", "Taper, coil definition, beard shape and edge."],
      color: ["Color, curl-safe", "Consultation required before any chemical service."],
      treatment: ["Deep Treatment", "Olaplex, protein or moisture reset as an add-on."],
      consult: ["Free 15-min consultation", "Dry assessment, no obligation, no pressure."],
      kids: ["Children's cut", "Under 12, dry shape and gentle finish."],
    },
    stylistNames: {
      any: ["No preference", "We'll pair you with the best fit for your pattern and service."],
      vanessa: ["Vanessa Jackson", "Founder. Type 4 dry cuts, shape resets and first-time consults."],
      iman: ["Iman Ali", "Color-safe curl work, porosity reads and finish education."],
      jonas: ["Jonas Bekele", "Sculpt Cut, taper, line, beard and coil definition."],
    },
    booking: {
      returningTitle: "Daniel, book the same again",
      returningBody: "Sculpt Cut with Vanessa. Last visit March 14. Next available Tuesday 18:30.",
      returningCta: "Rebook same cut",
      steps: ["Service", "Stylist", "Time", "Curl intake", "Confirm"],
      firstTime: "First visit",
      returning: "Returning",
      chooseService: "Choose the service",
      chooseStylist: "Choose the stylist",
      chooseTime: "Choose a real slot",
      intakeTitle: "Curl intake",
      intakeBody: "Optional, but it helps the stylist prepare. You can change this in the chair.",
      curlType: "Curl type",
      porosity: "Porosity",
      lastChemical: "Last chemical service",
      want: "What do you want",
      scared: "What are you scared of",
      skipIntake: "Skip intake",
      low: "Low",
      medium: "Medium",
      high: "High",
      confirmTitle: "Review and confirm",
      successTitle: "You're booked.",
      successBody: "SMS reminder 24h before. Prep email with tram directions and hair notes arrives the day before.",
      emailConfirmation: "A confirmation email has been sent to your inbox. Check your spam folder if you don't see it within a minute.",
      emailBookingIdLabel: "Booking ID",
      emailLabel: "Email",
      emailPlaceholder: "you@example.com",
      emailHint: "We send the booking confirmation here.",
      emailInvalid: "Please enter a valid email.",
      emailRequired: "Add an email to confirm.",
      phoneLabel: "Phone (optional)",
      phonePlaceholder: "+47 412 34 567",
      phoneHint: "Only used for SMS reminders 24h before.",
      emailSendCta: "Send me a copy",
      emailSending: "Sending…",
      emailSent: "Sent",
      addToCalendar: "Add to calendar",
      prep: "Arrive dry, detangled and in your natural pattern.",
      slots: ["Tue 18:30", "Wed 12:00", "Thu 19:15", "Fri 10:30", "Sat 14:00"],
    },
    services: sharedServices,
    stylists: sharedStylists,
    portfolio: [
      { title: "Day-three 4B shape reset", tag: "Type 4", image: images.portfolioType4 },
      { title: "3A cut with natural volume", tag: "Type 3", image: images.portfolioType3 },
      { title: "Fade, taper, coil definition", tag: "Sculpt Cut", image: images.portfolioSculpt },
      { title: "Dry cutting detail", tag: "Method", image: images.method },
      { title: "Long 3B definition reset", tag: "Type 3", image: images.portfolioExtra1 },
      { title: "Loose 3A natural volume", tag: "Type 3", image: images.portfolioExtra2 },
      { title: "Type 4 dry cut, mid-session", tag: "Type 4", image: images.portfolioExtra3 },
      { title: "First-visit 3B consult", tag: "Type 3", image: images.portfolioExtra4 },
    ],
    products: [
      ["Leave-in that behaves in winter", "Type 3-4", "220 NOK"],
      ["Rosemary scalp oil", "scalp + protective styles", "180 NOK"],
      ["Silky durag", "waves, coils, sleep", "260 NOK"],
      ["Twist sponge", "short Type 4 texture", "140 NOK"],
      ["Microfiber curl towel", "all patterns", "190 NOK"],
      ["Coily beard pick", "Sculpt Cut care", "120 NOK"],
    ],
    journal: [
      ["How to arrive for a dry cut", "No hats, no slick bun, no apology."],
      ["Porosity before product", "Why the shelf starts with how your hair takes water."],
      ["The Oslo fade-and-coils gap", "Daniel's service is not a men's add-on. It is a category."],
    ],
  },
  no: {
    messages: {
      app: { name: "Jackson & Coil", locale: "Norsk" },
    },
    nav: {
      home: "Hjem",
      services: "Klipp",
      team: "Team",
      portfolio: "Portfolio",
      method: "Metoden",
      shop: "Butikk",
      journal: "Journal",
      visit: "Besøk",
      about: "Om",
    },
    common: {
      skip: "Hopp til innhold",
      primaryNav: "Hovednavigasjon",
      mobileNav: "Mobilnavigasjon",
      toggleLanguage: "Bytt språk",
      openMenu: "Åpne meny",
      closeMenu: "Lukk meny",
      bookNow: "Book time",
      viewServices: "Se tjenester",
      readMethod: "Les metoden",
      minutes: "minutter",
      price: "Pris",
      duration: "Tid",
      next: "Neste",
      back: "Tilbake",
      confirm: "Bekreft booking",
    },
    labels: {
      photographyRule: "Fotoregelen",
      method: "Metode",
      founder: "Gründer",
      portfolio: "Portfolio",
      proof: "Bevis",
      proofTitle: "Standarden, helt konkret.",
      verifiedClient: "Prototype-sitat · Krøll-klient, Oslo",
      summary: "Oppsummering",
      service: "Tjeneste",
      stylist: "Stylist",
      time: "Tid",
      with: "med",
      nextAvailable: "Neste ledige",
      available: "Ledig",
      core: "Kjerne",
      openingHours: "Åpningstider",
      closed: "Søn-man stengt",
      location: "Grünerløkka, Oslo",
      noChemicalPlaceholder: "Ingen / farge / relaxer",
      wantPlaceholder: "Form, lengde, definition, line",
      scaredPlaceholder: "For kort, shrinkage, ujevn form",
    },
    footer: {
      eyebrow: "Grünerløkka, Oslo",
      title: "Tørr konsultasjon først. Så klippen.",
      body: "En krøllspesialist for hele spekteret, med prisene på siden og booking som blir inne i merkevaren.",
      visit: "Besøk salongen",
      navigate: "Naviger",
      details: "Detaljer",
    },
    home: {
      eyebrow: "Grunnlagt av Vanessa Jackson",
      title: "Oslos første salong bygget rundt hele curl spectrum.",
      lead: "Fra løse bølger til tette coils får hvert mønster samme faglige behandling, hos stylister som faktisk har trent på det.",
      proof: ["Gratis 15 min tørr konsultasjon", "Type 2A-4C", "Pris før du booker"],
      imageNote: "Hero-rotasjon: Amara og Daniel, over folden, ikke en egen herreside.",
      band: "Spectrum er arbeidsordet. Én stol for coils, krøller, bølger, fade og shape-up.",
      bookingTitle: "Booking er en del av klippen.",
      bookingBody: "Velg tjeneste, stylist, reell ledig tid og krølltype uten å forlate siden. Ingen widget-redirect, ingen kontaktskjema-felle.",
      servicesTitle: "Tre veier inn.",
      methodTitle: "The Jackson Cut kartlegger håret før det klippes.",
      methodBody: "Vurdering, kart, tørr klipp, finish, opplæring. Metoden er synlig fordi tillit ikke skal bygges på stemning alene.",
      founderTitle: "Vanessa, på jobb.",
      founderBody: "Trent ved Curl Bar London og Devachan NYC. Salongen er det som skjer når hun slutter å låne stoler hos andre.",
      portfolioTitle: "Samme vegg. Hele spekteret.",
      portfolioBody: "Type 4 er hjemmebasen. Type 3 ligger i galleriet. Daniels Sculpt Cut er integrert fra dag én.",
      visitTitle: "Et varmt rom, ikke en forestilling.",
      visitBody: "Papirvarme vegger, terrakottadetalj, ekte dagslys og retail som løser Norge-gapet.",
      testimonials: [
        { quote: "Ingen spurte om håret mitt var for mye.", attribution: "Amara O. · Type 4a · Tøyen" },
        { quote: "Jeg booket på mobilen etter leggetid og hadde time på under to minutter.", attribution: "Sigrid M. · Type 2c · Frogner" },
        { quote: "Faden og coilene skjedde i samme stol.", attribution: "Daniel B. · Sculpt · Grünerløkka" },
        { quote: "Prisene sto der før jeg trykket videre.", attribution: "Maja H. · Type 3b · Sagene" },
      ],
    },
    servicesPage: {
      eyebrow: "Klipp og tjenester",
      title: "Én pris, synlig før stolen.",
      lead: "Første besøk inkluderer tørr konsultasjon. Farge starter med konsultasjon. Herrearbeid handler om sculpt, taper, definition og line.",
      prepTitle: "Kom tørr, flokefri, naturlig.",
      prep: "Ingen lue, klemmer, fletter, stram bun eller strekkede frisyrer som endrer mønsteret. Ta med bilder hvis det hjelper. Vi må se håret før vi tar i det.",
      pricingTitle: "Ingen gjetting i kassen.",
      pricingBody: "Alle tjenester viser pris og tid. Farge har publisert spenn fordi arbeidet varierer, men konsultasjonen skjer før prisen endres.",
    },
    methodPage: {
      eyebrow: "Metoden",
      title: "Tørt først. Mønsteret synlig. Klipp etterpå.",
      lead: "The Jackson Cut og The Sculpt Cut er bygget som lærbare systemer, ikke personlige triks.",
      steps: [
        ["Vurder", "Krølltype, tetthet, porøsitet, vekstretning og hvordan håret faktisk lever dag tre."],
        ["Kartlegg", "Topplag, underlag, nakke og tinning får ulike regler."],
        ["Klipp", "Tørt, krøll for krøll, uten å strekke mønsteret til noe det ikke er."],
        ["Fullfør", "Produkter du får tak i i Norge og kan bruke hjemme uten teater."],
        ["Forklar", "Du går ut med forståelse for hva som ble gjort og hvorfor."],
      ],
      diagramTitle: "Vi bruker Andre Walkers 2A til 4C-skala i konsultasjonen.",
      diagramBody: "Det er ikke en merkelapp som definerer deg. Det er et felles språk så stylisten kan forberede seg før du kommer.",
    },
    teamPage: {
      eyebrow: "Teamet",
      title: "Navngitte stylister før kalenderen.",
      lead: "Velg Vanessa, velg en spesialist, eller velg ingen preferanse. Du straffes ikke for å ville ha best match.",
    },
    aboutPage: {
      eyebrow: "Gründerhistorien",
      title: "Salongen er det som skjer når Vanessa slutter å låne stoler.",
      lead: "Nord-London-trening, New York-teknikk og Oslo-kunder som var lei av å fly ut for klipp.",
      body: "Vanessa Jackson trente formelt ved Curl Bar London under Michelle Sultan, før hun dro til New York for inspirasjon fra Devachan og Hair Rules. I Oslo bygget hun en stille kundeliste fra lånte stoler. Jackson & Coil gjør stolen til en flaggskipssalong.",
      belief: "Every curl pattern er samme jobb gjort med kunnskap, og kunnskap er noe du går og henter.",
    },
    visitPage: {
      eyebrow: "Besøk",
      title: "Grünerløkka, nær trikken, bygget for ekte avtaler.",
      lead: "Varmt lys, skarpe kanter, ingen spa-teater. Rommet er rolig fordi arbeidet er presist.",
      directions: ["Trikk 11, 12 eller 13 til Olaf Ryes plass", "Fem minutter fra Birkelunden", "Trinnfri inngang planlagt", "Kveldstimer tirsdag til fredag"],
    },
    portfolioPage: {
      eyebrow: "Portfolio",
      title: "Ett galleri. Ingen barnebord.",
      lead: "Filtrer etter mønster hvis det hjelper, men arbeidet står samlet. Veggen skal fortelle sannheten på tre sekunder.",
      filters: ["Alle", "Type 4", "Type 3", "Sculpt Cut"],
    },
    shopPage: {
      eyebrow: "Butikk",
      title: "Hyllen Oslo har manglet.",
      lead: "Et stramt retail-utvalg: krøllprodukter, durags, bonnets, twist sponges, beard picks og de kjedelige basisvarene folk faktisk kjøper igjen.",
    },
    journalPage: {
      eyebrow: "Journal",
      title: "Kort, nyttig, ikke innhold for innholdets skyld.",
      lead: "Forberedelser, produktkunnskap, Vanessas stemme og community-kvelder. Skrevet som av noen som har stått bak stolen.",
    },
    bookingPage: {
      eyebrow: "Booking",
      title: "Book på mobilen på to minutter.",
      lead: "Velg tjeneste, stylist og tid. Bekreft på to minutter.",
    },
    serviceNames: {
      first: ["Første besøk", "Konsultasjon + Jackson Cut + finish + førstegangs-rabatt på retail."],
      jackson: ["The Jackson Cut", "Tørr, krøll-for-krøll-klipp for Type 2-4 hår."],
      sculpt: ["The Sculpt Cut", "Fade, lineup og tørr coil-forming i samme stol."],
      "sculpt-beard": ["Sculpt Cut + Beard", "Taper, coil definition, skjeggform og edge."],
      color: ["Farge, curl-safe", "Konsultasjon kreves før kjemisk behandling."],
      treatment: ["Deep Treatment", "Olaplex, protein eller fuktreset som tillegg."],
      consult: ["Gratis 15 min konsultasjon", "Tørr vurdering, ingen forpliktelse, ikke press."],
      kids: ["Barneklipp", "Under 12, tørr form og rolig finish."],
    },
    stylistNames: {
      any: ["Ingen preferanse", "Vi matcher deg med riktig stylist for mønster og tjeneste."],
      vanessa: ["Vanessa Jackson", "Gründer. Type 4 tørrklipp, form-reset og førstegangs-konsultasjon."],
      iman: ["Iman Ali", "Fargesikker krølljobb, porøsitet og opplæring i finish."],
      jonas: ["Jonas Bekele", "Sculpt Cut, taper, line, skjegg og coil definition."],
    },
    booking: {
      returningTitle: "Daniel, book samme klipp igjen",
      returningBody: "Sculpt Cut med Vanessa. Siste besøk 14. mars. Neste ledige tirsdag 18:30.",
      returningCta: "Book samme klipp igjen",
      steps: ["Tjeneste", "Stylist", "Tid", "Krøll-intak", "Bekreft"],
      firstTime: "Første besøk",
      returning: "Tilbake",
      chooseService: "Velg tjeneste",
      chooseStylist: "Velg stylist",
      chooseTime: "Velg en reell tid",
      intakeTitle: "Krøll-intak",
      intakeBody: "Valgfritt, men det hjelper stylisten å forberede seg. Du kan endre det i stolen.",
      curlType: "Krølltype",
      porosity: "Porøsitet",
      lastChemical: "Siste kjemiske behandling",
      want: "Hva ønsker du",
      scared: "Hva er du redd for",
      skipIntake: "Hopp over intak",
      low: "Lav",
      medium: "Medium",
      high: "Høy",
      confirmTitle: "Se over og bekreft",
      successTitle: "Du er booket.",
      successBody: "SMS-påminnelse 24 timer før. Prep-epost med trikkerute og hårnotater kommer dagen før.",
      emailConfirmation: "En bekreftelse er sendt til e-posten din. Sjekk søppelpost om du ikke ser den innen et minutt.",
      emailBookingIdLabel: "Booking-ID",
      emailLabel: "E-post",
      emailPlaceholder: "deg@eksempel.no",
      emailHint: "Vi sender bookingbekreftelsen hit.",
      emailInvalid: "Skriv en gyldig e-postadresse.",
      emailRequired: "Legg til e-post for å bekrefte.",
      phoneLabel: "Telefon (valgfritt)",
      phonePlaceholder: "+47 412 34 567",
      phoneHint: "Brukes bare til SMS-påminnelse 24 t før.",
      emailSendCta: "Send kopi til meg",
      emailSending: "Sender…",
      emailSent: "Sendt",
      addToCalendar: "Legg til i kalender",
      prep: "Kom tørr, flokefri og med naturlig mønster.",
      slots: ["Tir 18:30", "Ons 12:00", "Tor 19:15", "Fre 10:30", "Lør 14:00"],
    },
    services: sharedServices,
    stylists: sharedStylists,
    portfolio: [
      { title: "Dag-tre 4B form-reset", tag: "Type 4", image: images.portfolioType4 },
      { title: "3A-klipp med naturlig volum", tag: "Type 3", image: images.portfolioType3 },
      { title: "Fade, taper, coil definition", tag: "Sculpt Cut", image: images.portfolioSculpt },
      { title: "Detalj fra tørr klipp", tag: "Metode", image: images.method },
      { title: "Langt 3B-hår, definisjons-reset", tag: "Type 3", image: images.portfolioExtra1 },
      { title: "Løse 3A, naturlig volum", tag: "Type 3", image: images.portfolioExtra2 },
      { title: "Type 4, midt i tørrklipp", tag: "Type 4", image: images.portfolioExtra3 },
      { title: "Førstebesøk 3B-konsultasjon", tag: "Type 3", image: images.portfolioExtra4 },
    ],
    products: [
      ["Leave-in som tåler vinter", "Type 3-4", "220 NOK"],
      ["Rosemary scalp oil", "hodebunn + protective styles", "180 NOK"],
      ["Silky durag", "waves, coils, søvn", "260 NOK"],
      ["Twist sponge", "kort Type 4 tekstur", "140 NOK"],
      ["Microfiber curl towel", "alle mønstre", "190 NOK"],
      ["Coily beard pick", "Sculpt Cut care", "120 NOK"],
    ],
    journal: [
      ["Slik kommer du til tørrklipp", "Ingen lue, ingen slick bun, ingen unnskyldning."],
      ["Porøsitet før produkt", "Hvorfor hyllen starter med hvordan håret tar vann."],
      ["Oslo-gapet for fade og coils", "Daniels tjeneste er ikke et herre-tillegg. Det er en kategori."],
    ],
  },
} as const;
